apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
 annotations:
 name: microservice-ui 
 namespace: default
spec:
 maxReplicas: 10
 minReplicas: 1
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: microservice-ui 
 metrics:
 - type: Resource
   resource:
     name: cpu
     targetAverageUtilization: 1
