apiVersion: v1
kind: Service
metadata:
  name: nodejs-webapp
  labels:
    app: nodejs-webapp
spec:
  ports:
   - port: 3000
     protocol: TCP
     nodePort: 30000
  selector:
    app: nodejs-webapp
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nodejs-webapp
  labels: 
    app: nodejs-webapp
spec:
  selector: 
    matchLabels:
      app: nodejs-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-webapp
    spec:
      containers:
        - name: nodejs-webapp
          image: juliepwchen/insightdemo_nodejs
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
